### ISSUE TITLE
请教程序问题

### ISSUE THREAD

**Issue by cino-versionK** [Dengsgithub/DRD-Net#3]
Thanks.

  ValueError: Found unexpected keys that do not correspond to any Model output: dict_keys(['subtract_1', 'add_36']). Expected: ['subtract', 'add_35']

**Comment by cino-versionK** [comment]
ValueError: could not broadcast input array from shape (0,128,3) into shape (128,128,3)

**Comment by wblyqq** [comment]
> ValueError: could not broadcast input array from shape (0,128,3) into shape (128,128,3)

输入的数据和label不对应，你重新写一下数据的读入
