### ISSUE TITLE
关于训练

### ISSUE THREAD

**Issue by chenzhengdeeplearning** [Dengsgithub/DRD-Net#6]

**Comment by Joyies** [comment]
> 您好，我按照您的readme文件，在训练200L数据集时将If_n设置成false。 可是训练过程中验证集的psnr一直都是负的，而且我在训练200L200H和RAIN800时，都出现了损失不收敛的情况，想向您请教一下，这是怎么回事。另外我近期有一份去雨相关的工作正在撰写，想引入您的这篇文章作为对比算法，恳请您能否方便提供一下您的预训练权重？十分感谢！也十分期待您的回复！我的邮箱是[chenzheng@hrbeu.edu.cn](mailto:chenzheng@hrbeu.edu.cn) 祝您工作顺利，身体健康！再次感谢！

您复现出了结果吗

**Comment by LeeYiZhou** [comment]
源码里面学习率默认是0.1，对于Adam来说太高了。改成paper中的0.01后loss可以顺利收敛

**Comment by chenzhengdeeplearning** [comment]
> 您好，我按照您的readme文件，在训练200L数据集时将If_n设置成false。 可是训练过程中验证集的psnr一直都是负的，而且我在训练200L200H和RAIN800时，都出现了损失不收敛的情况，想向您请教一下，这是怎么回事。另外我近期有一份去雨相关的工作正在撰写，想引入您的这篇文章作为对比算法，恳请您能否方便提供一下您的预训练权重？十分感谢！也十分期待您的回复！我的邮箱是[chenzheng@hrbeu.edu.cn](mailto:chenzheng@hrbeu.edu.cn) 祝您工作顺利，身体健康！再次感谢！



> 您好，我按照您的readme文件，在训练200L数据集时将If_n设置成false。 可是训练过程中验证集的psnr一直都是负的，而且我在训练200L200H和RAIN800时，都出现了损失不收敛的情况，想向您请教一下，这是怎么回事。另外我近期有一份去雨相关的工作正在撰写，想引入您的这篇文章作为对比算法，恳请您能否方便提供一下您的预训练权重？十分感谢！也十分期待您的回复！我的邮箱是[chenzheng@hrbeu.edu.cn](mailto:chenzheng@hrbeu.edu.cn) 祝您工作顺利，身体健康！再次感谢！
